@startuml
'https://plantuml.com/sequence-diagram

actor "Ship Captain" as SC
participant ": CargoManifestPerYearUI" as UI
participant ": CargoManifestPerYearController" as CT
participant ": Company" as CP
participant "store : CargoManifestStore" as ST
participant "cargoManifest : CargoManifest" as CM


activate SC
SC->UI : starts the requisition of the ratio between\n number of container and the capacity of a ship
activate UI
UI --> SC : asks the id of the cargo manifest
deactivate UI
SC -> UI : type the id of the cargo manifest
activate UI
UI->CT : getTheRatioOfCargoManifest(id)
activate CT
CT-> CP : store = getCargoManifestStore()
activate CP
deactivate CP
CT -> ST : getRatioOfACargoManifestById(id)
activate ST
ST -> CM : ratio = getRatio()
activate CM
deactivate CM
deactivate ST

deactivate CT
UI-->SC : show the ratio between the number \nof containers e the capacity of a ship
deactivate UI
deactivate SC

@enduml