@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Traffic Manager" as TM
participant ":CreateFreightNetworkUI  " as UI
participant ":CreateFreightNetworkController" as CTRL
participant ":Company" as CMP


activate TM
TM -> UI: Initiates the process to create a freight \n network importing ports, countries,\n borders and seadists from database
activate UI
UI -> CTRL : createFreightNetwork()
activate CTRL
deactivate CTRL

UI --> TM : Informs of operation success
deactivate UI

deactivate TM

@enduml