@startuml
autonumber

actor "Client" as C
participant "FindContainerSituationUi" as UI

activate C
C -> UI:  Initiates the process to get the current\n situation of a specific container
activate UI
UI --> C : Request the e container identifier
deactivate UI
C -> UI : Introduce the requested data

activate UI
UI-->C : Show the current location
deactivate UI
deactivate C
@enduml



activate C

C -> CSUI: want to know the current status of a specific container
activate CSUI
CSUI --> C: asks for container code (id)
deactivate CSUI
C -> CSUI:  type the requested data.

activate CSUI
CSUI -> COC: createUS204 (id)
activate COC

COC -> US: create (id)
activate US


US -> US:initialize (id)
US -> WT: WriteToFile(info)
activate WT
deactivate WT


deactivate COC
CSUI --> C: shows the information.

deactivate CSUI
deactivate C
@enduml