@startuml
'https://plantuml.com/sequence-diagram

class ShipsIdleUI{
}

class ShipsIdleController{
+ createShipsIdle()
}


class ShipsIdle {
- initialize()
+ toString()
}

class WriteForAFile{
+ writeForAFiLe(textualInformation : String)
}

ShipsIdleUI ..> ShipsIdleController
ShipsIdleController-> ShipsIdle
ShipsIdle --> WriteForAFile : uses
@enduml