@startuml
'https://plantuml.com/use-case-diagram
left to right direction
actor "Traffic Manager" as TM
actor "Project Manager" as PM
actor "Client" as C
actor "Ship Captain" as SC

rectangle Company{

usecase "UC101: I which to import ships from a text file into a BST" as UC101
usecase "UC102: I which to search the details of a ship using \n any of its codes: MMSI, IMO or Call Sign" as UC102
usecase "UC103: I which to have the positional messages temporally \n organized and associated with each of the ships " as UC103
usecase "UC104: I which to make a Summary of a ship's movements" as UC104
usecase "UC105: I which to list for all ships the MMSI, the total number of movements,\n Travelled Distance and Delta Distance." as UC105
usecase "UC106: Get the top-N ships with the most kilometres travelled and their average speed (MeanSOG)." as UC106
usecase "UC107: Return pairs of ships with routes with close departure/arrival \ncoordinates (no more than 5 Kms away) and with different Travelled Distance." as UC107
usecase "UC108: I want the team to develop the data model required to support\n all the functionality and to fulfill the purpose of the system to develop.\n This data model is to be designed following a systematic data modeling methodology. " as UC108
usecase "UC109: I want the team to draft an SQL script to test whether the database \n verifies all the data integrity restrictions that are required to fulfil \n the purpose of the system and the business constraints of the UoD" as UC109
usecase "UC110: I want the team to define the naming conventions to \n apply when defining identifiers or writing SQL or PL/SQL code.\n The naming conventions may evolve as new database and programming objects are known.\n The naming conventions guide should be organized in a way to facilitate its maintenance" as UC110
usecase "UC111: I want the team to create a SQL script to load the database\n with a minimum set of data sufficient to carry out data integrity verification \n and functional testing. This script shall produce a bootstrap report \n providing the number of tuples/rows in each relation/table" as UC111

usecase "UC201: I which to import ports from a text file and create a 2D-tree with port locations." as UC201
usecase "UC202: I which to find the closest port of a ship given its CallSign, on a certain DateTime" as UC202
usecase "UC203: I want the team to review the relational data model in view \nof the new user stories so it can support all the requirements to \nfulfil the purpose of the system being developed. " as UC203
usecase "UC204: I want to know the current situation of a specific container being used to transport my goods." as UC204
usecase "UC205: I want the list of containers to be offloaded in the next port, \nincluding container identifier, type, position, and load." as UC205
usecase "UC206: I want the list of containers to be loaded in the next port, \nincluding container identifier, type, and load." as UC206
usecase "UC207: I want to know how many cargo manifests I have transported during a \ngiven year and the average number of containers per manifest." as UC207
usecase "UC208: I want to know the occupancy rate (percentage) of a given ship \nfor a given cargo manifest. Occupancy rate is the ratio between total number of containers \nin the ship coming from a given manifest and the total capacity of the ship, i.e., the \nmaximum number of containers the ship can load." as UC208
usecase "UC209: I want to know the occupancy rate of a given ship at a given moment." as UC209
usecase "UC210: I need to know which ships will be available on Monday next week and their location" as UC210


}

TM-----UC101
TM----UC102
TM----UC103
TM----UC104
TM----UC105
TM----UC106
TM----UC107
PM----UC108
PM----UC109
PM----UC110
PM----UC111

UC201 ---- PM
UC202 ---- TM
UC203 ---- PM
UC204 ---- C
UC205 ---- SC
UC206 ---- SC
UC207 ---- SC
UC208 ---- SC
UC209 ---- SC
UC210 ---- TM



@enduml