@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Ships {
-mmsiCode
-name
-imoCode
-numberEnergyGenerators
-generatorPower
-callSign
-vesselType
-length
-width
-capacity
-draft
}

class ShipPosition {
-baseDateTime
-latitude
-longitude
-sog
-cog
-heading
-position
-transceiver
}

class BstShip {
-getShipByMmsiCode(mmsiCode)
}

class BstShipPosition {
-getPositinalMessages(initialDate, finalDate)
}

class ShowPositionalMessagesUI {}

class ShowPositionalMessagesController {
-shipExist(mmsiCode)
-showPositionalMessages(initialDate, finalDate)
}

class Company {
-designation
-getBstShip(mmsiCode)
}

BstShip "1" -- "1..*" Ships : owns >
BstShipPosition "1" -- "1..*" ShipPosition : has >

Company "1" -- "1" BstShip : uses >

Ships "1" -- "1" BstShipPosition : uses >

ShowPositionalMessagesUI ..> ShowPositionalMessagesController

ShowPositionalMessagesController ..> Company
ShowPositionalMessagesController ..> BstShip
ShowPositionalMessagesController ..> Ships
ShowPositionalMessagesController ..> BstShipPosition


@enduml