@startuml
'https://plantuml.com/class-diagram
actor "Ship Captain" as SC
participant "System" as SY
participant "LoadUnloadController" as CTR
participant ":Company" as CP
participant "store : CargoManifestStore" as ST

activate SC
SC -> SY : starts the requisition of the list \n of containers to be loaded in the next port
activate SY



SY --> SC : asks the ship
deactivate SY
SC -> SY : type the ship

activate SY
SY -> CTR: findRespectiveShip(mmsi)
activate CTR
CTR -> CP : bstShip = getBstShip()
activate CP
deactivate CP

CTR -> CTR: ship = shipExist(mmsiCode)
activate CTR
deactivate CTR
CTR -> CTR : destination = findDestination()
activate CTR
deactivate CTR
CTR ->CP : store = getCargoManifestStore()
activate CP
deactivate CP
CTR -> ST :loadList = getShipCargoManifestsAccordingToDestination(ship,destination)
activate ST
deactivate ST

CTR --> SY : loadList

deactivate CTR
SY --> SC : shows the list of containers
deactivate SY
deactivate SC
@enduml